<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="ackermann_drive_controller" params="wheel_separation wheel_radius wheel_torque">
    <gazebo>
      <plugin name="ackermann_drive" filename="libgazebo_ros_ackermann_drive.so">
        <ros>
          <argument>odom:=odom/unfiltered</argument>
          <!--<argument>tf:=dummy_tf</argument>-->
        </ros>
        <updateRate>100</updateRate>
        <front_left_joint>front_left_wheel_joint</front_left_joint>
        <front_right_joint>front_right_wheel_joint</front_right_joint>
        <rear_left_joint>rear_left_wheel_joint</rear_left_joint>
        <rear_right_joint>rear_right_wheel_joint</rear_right_joint>
        <left_steering_joint>front_left_steering_joint</left_steering_joint>
        <right_steering_joint>front_right_steering_joint</right_steering_joint>

        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

        <max_speed>20.0</max_speed>
        <max_steer>5.0</max_steer>
        <max_steering_angle>0.85</max_steering_angle>

        <robot_base_frame>base_footprint</robot_base_frame>
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>true</publish_wheel_tf>
        <odometry_frame>odom</odometry_frame>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>